<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<TIMETABLE_CLASSES>
  <TLIMIT X="0" VALUE="8"/>
  <TLIMIT X="1" VALUE="8"/>
  <TLIMIT X="2" VALUE="8"/>
  <TLIMIT X="3" VALUE="8"/>
  <TLIMIT X="4" VALUE="8"/>
  <TSLOTUNIT VALUE="0"/>
  <TMPD VALUE="4"/>
  <DAY_GROUP X="0" VALUE="1"/>
  <DAY_GROUP X="1" VALUE="1"/>
  <DAY_GROUP X="2" VALUE="1"/>
  <DAY_GROUP X="3" VALUE="1"/>
  <DAY_GROUP X="4" VALUE="1"/>
  <TIME_SLOT_NAME X="0" Y="0" VALUE="RM"/>
  <TIME_SLOT_NAME X="0" Y="1" VALUE="P.1"/>
  <TIME_SLOT_NAME X="0" Y="2" VALUE="P.2"/>
  <TIME_SLOT_NAME X="0" Y="3" VALUE="L.1"/>
  <TIME_SLOT_NAME X="0" Y="4" VALUE="L.2"/>
  <TIME_SLOT_NAME X="0" Y="5" VALUE="P.3"/>
  <TIME_SLOT_NAME X="0" Y="6" VALUE="L.3"/>
  <TIME_SLOT_NAME X="0" Y="7" VALUE="P.4"/>
  <TIME_SLOT_NAME X="1" Y="0" VALUE="RM"/>
  <TIME_SLOT_NAME X="1" Y="1" VALUE="P.1"/>
  <TIME_SLOT_NAME X="1" Y="2" VALUE="P.2"/>
  <TIME_SLOT_NAME X="1" Y="3" VALUE="L.1"/>
  <TIME_SLOT_NAME X="1" Y="4" VALUE="L.2"/>
  <TIME_SLOT_NAME X="1" Y="5" VALUE="P.3"/>
  <TIME_SLOT_NAME X="1" Y="6" VALUE="L.3"/>
  <TIME_SLOT_NAME X="1" Y="7" VALUE="P.4"/>
  <TIME_SLOT_NAME X="2" Y="0" VALUE="RM"/>
  <TIME_SLOT_NAME X="2" Y="1" VALUE="P.1"/>
  <TIME_SLOT_NAME X="2" Y="2" VALUE="P.2"/>
  <TIME_SLOT_NAME X="2" Y="3" VALUE="L.1"/>
  <TIME_SLOT_NAME X="2" Y="4" VALUE="L.2"/>
  <TIME_SLOT_NAME X="2" Y="5" VALUE="P.3"/>
  <TIME_SLOT_NAME X="2" Y="6" VALUE="L.3"/>
  <TIME_SLOT_NAME X="2" Y="7" VALUE="P.4"/>
  <TIME_SLOT_NAME X="3" Y="0" VALUE="RM"/>
  <TIME_SLOT_NAME X="3" Y="1" VALUE="P.1"/>
  <TIME_SLOT_NAME X="3" Y="2" VALUE="P.2"/>
  <TIME_SLOT_NAME X="3" Y="3" VALUE="L.1"/>
  <TIME_SLOT_NAME X="3" Y="4" VALUE="L.2"/>
  <TIME_SLOT_NAME X="3" Y="5" VALUE="P.3"/>
  <TIME_SLOT_NAME X="3" Y="6" VALUE="L.3"/>
  <TIME_SLOT_NAME X="3" Y="7" VALUE="P.4"/>
  <TIME_SLOT_NAME X="4" Y="0" VALUE="RM"/>
  <TIME_SLOT_NAME X="4" Y="1" VALUE="P.1"/>
  <TIME_SLOT_NAME X="4" Y="2" VALUE="P.2"/>
  <TIME_SLOT_NAME X="4" Y="3" VALUE="L.1"/>
  <TIME_SLOT_NAME X="4" Y="4" VALUE="L.2"/>
  <TIME_SLOT_NAME X="4" Y="5" VALUE="P.3"/>
  <TIME_SLOT_NAME X="4" Y="6" VALUE="L.3"/>
  <TIME_SLOT_NAME X="4" Y="7" VALUE="P.4"/>
  <TSCODE X="0" Y="0" VALUE="R"/>
  <TSCODE X="0" Y="1" VALUE="1"/>
  <TSCODE X="0" Y="2" VALUE="2"/>
  <TSCODE X="0" Y="3" VALUE="A"/>
  <TSCODE X="0" Y="4" VALUE="B"/>
  <TSCODE X="0" Y="5" VALUE="3"/>
  <TSCODE X="0" Y="6" VALUE="C"/>
  <TSCODE X="0" Y="7" VALUE="4"/>
  <TSCODE X="1" Y="0" VALUE="R"/>
  <TSCODE X="1" Y="1" VALUE="1"/>
  <TSCODE X="1" Y="2" VALUE="2"/>
  <TSCODE X="1" Y="3" VALUE="A"/>
  <TSCODE X="1" Y="4" VALUE="B"/>
  <TSCODE X="1" Y="5" VALUE="3"/>
  <TSCODE X="1" Y="6" VALUE="C"/>
  <TSCODE X="1" Y="7" VALUE="4"/>
  <TSCODE X="2" Y="0" VALUE="R"/>
  <TSCODE X="2" Y="1" VALUE="1"/>
  <TSCODE X="2" Y="2" VALUE="2"/>
  <TSCODE X="2" Y="3" VALUE="A"/>
  <TSCODE X="2" Y="4" VALUE="B"/>
  <TSCODE X="2" Y="5" VALUE="3"/>
  <TSCODE X="2" Y="6" VALUE="C"/>
  <TSCODE X="2" Y="7" VALUE="4"/>
  <TSCODE X="3" Y="0" VALUE="R"/>
  <TSCODE X="3" Y="1" VALUE="1"/>
  <TSCODE X="3" Y="2" VALUE="2"/>
  <TSCODE X="3" Y="3" VALUE="A"/>
  <TSCODE X="3" Y="4" VALUE="B"/>
  <TSCODE X="3" Y="5" VALUE="3"/>
  <TSCODE X="3" Y="6" VALUE="C"/>
  <TSCODE X="3" Y="7" VALUE="4"/>
  <TSCODE X="4" Y="0" VALUE="R"/>
  <TSCODE X="4" Y="1" VALUE="1"/>
  <TSCODE X="4" Y="2" VALUE="2"/>
  <TSCODE X="4" Y="3" VALUE="A"/>
  <TSCODE X="4" Y="4" VALUE="B"/>
  <TSCODE X="4" Y="5" VALUE="3"/>
  <TSCODE X="4" Y="6" VALUE="C"/>
  <TSCODE X="4" Y="7" VALUE="4"/>
  <TSALLOT X="0" Y="0" VALUE="20"/>
  <TSALLOT X="0" Y="1" VALUE="70"/>
  <TSALLOT X="0" Y="2" VALUE="70"/>
  <TSALLOT X="0" Y="3" VALUE="20"/>
  <TSALLOT X="0" Y="4" VALUE="20"/>
  <TSALLOT X="0" Y="5" VALUE="70"/>
  <TSALLOT X="0" Y="6" VALUE="20"/>
  <TSALLOT X="0" Y="7" VALUE="70"/>
  <TSALLOT X="1" Y="0" VALUE="20"/>
  <TSALLOT X="1" Y="1" VALUE="70"/>
  <TSALLOT X="1" Y="2" VALUE="70"/>
  <TSALLOT X="1" Y="3" VALUE="20"/>
  <TSALLOT X="1" Y="4" VALUE="20"/>
  <TSALLOT X="1" Y="5" VALUE="70"/>
  <TSALLOT X="1" Y="6" VALUE="20"/>
  <TSALLOT X="1" Y="7" VALUE="70"/>
  <TSALLOT X="2" Y="0" VALUE="20"/>
  <TSALLOT X="2" Y="1" VALUE="70"/>
  <TSALLOT X="2" Y="2" VALUE="70"/>
  <TSALLOT X="2" Y="3" VALUE="20"/>
  <TSALLOT X="2" Y="4" VALUE="20"/>
  <TSALLOT X="2" Y="5" VALUE="70"/>
  <TSALLOT X="2" Y="6" VALUE="20"/>
  <TSALLOT X="2" Y="7" VALUE="70"/>
  <TSALLOT X="3" Y="0" VALUE="20"/>
  <TSALLOT X="3" Y="1" VALUE="70"/>
  <TSALLOT X="3" Y="2" VALUE="70"/>
  <TSALLOT X="3" Y="3" VALUE="20"/>
  <TSALLOT X="3" Y="4" VALUE="20"/>
  <TSALLOT X="3" Y="5" VALUE="70"/>
  <TSALLOT X="3" Y="6" VALUE="20"/>
  <TSALLOT X="3" Y="7" VALUE="70"/>
  <TSALLOT X="4" Y="0" VALUE="20"/>
  <TSALLOT X="4" Y="1" VALUE="70"/>
  <TSALLOT X="4" Y="2" VALUE="70"/>
  <TSALLOT X="4" Y="3" VALUE="20"/>
  <TSALLOT X="4" Y="4" VALUE="20"/>
  <TSALLOT X="4" Y="5" VALUE="70"/>
  <TSALLOT X="4" Y="6" VALUE="20"/>
  <TSALLOT X="4" Y="7" VALUE="70"/>
</TIMETABLE_CLASSES>